apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: n8n-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      array:
        - |
          objectName: "db-user"
          objectType: "secretsmanager"
        - |
          objectName: "db-password"
          objectType: "secretsmanager"
  secretObjects:
    - secretName: n8n-container-env
      type: Opaque
      data:
        - objectName: db-user
          key: DB_POSTGRESDB_USER
        - objectName: db-password
          key: DB_POSTGRESDB_PASSWORD
