apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: n8n-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: "db_user"
            objectAlias: "db-user"
          - path: "db_password"
            objectAlias: "db-password"
          - path: "db_host"
            objectAlias: "db-host"
          - path: "db_name"
            objectAlias: "db-name"
  secretObjects:
    - secretName: n8n-container-env
      type: Opaque
      data:
        - objectName: db-user
          key: DB_POSTGRESDB_USER
        - objectName: db-password
          key: DB_POSTGRESDB_PASSWORD
        - objectName: db-host
          key: DB_POSTGRESDB_HOST
        - objectName: db-name
          key: DB_POSTGRESDB_DATABASE
